name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: |
          cp .env.prod .env
          sed -i "s/{APP_KEY}/${{ secrets.APP_KEY }}/g"
          sed -i "s/{DB_USERNAME}/${{ secrets.DB_USERNAME }}/g"
          sed -i "s/{DB_PASSWORD}/${{ secrets.DB_PASSWORD }}/g"
          sed -i "s/{GOOGLE_CLIENT_ID}/${{ secrets.GOOGLE_CLIENT_ID }}/g"
          sed -i "s/{GOOGLE_SECRET}/${{ secrets.GOOGLE_SECRET }}/g"

      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy build to VPS
        run: |
          rsync -avz --progress --delete ${{ github.workspace }}  ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html/accounts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /var/www/html/accounts
            php8.3 artisan migrate --force
            php8.3 artisan optimize
            chown -R www-data:www-data *
